package org.framework.entity;
// Generated 05 31, 18 11:14:50 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PaymentUserMapping generated by hbm2java
 */
@Entity
@Table(name = "payment_user_mapping", catalog = "petshop")
public class PaymentUserMapping implements java.io.Serializable {

	/**  @Author AdityaPandey
	 *   9 Jun 2018
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private PaymentStatus paymentStatus;
	private Pet pet;
	private User user;

	public PaymentUserMapping() {
	}

	public PaymentUserMapping(PaymentStatus paymentStatus, Pet pet, User user) {
		this.paymentStatus = paymentStatus;
		this.pet = pet;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_status_Id")
	public PaymentStatus getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(PaymentStatus paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pet_Id")
	public Pet getPet() {
		return this.pet;
	}

	public void setPet(Pet pet) {
		this.pet = pet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_Id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
