package org.framework.entity;
// Generated 05 31, 18 11:14:50 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentStatus generated by hbm2java
 */
@Entity
@Table(name = "payment_status", catalog = "petshop")
public class PaymentStatus implements java.io.Serializable {

	/**  @Author AdityaPandey
	 *   9 Jun 2018
	 */
	private static final long serialVersionUID = 1L;
	private Integer paymentStatusId;
	private String paymentType;
	private String cardHolderName;
	private Long accountNumber;
	private String paymentStatus;
	private Set<PaymentUserMapping> paymentUserMappings = new HashSet<PaymentUserMapping>(0);

	public PaymentStatus() {
	}

	public PaymentStatus(String paymentType, String cardHolderName, Long accountNumber, String paymentStatus,
			Set<PaymentUserMapping> paymentUserMappings) {
		this.paymentType = paymentType;
		this.cardHolderName = cardHolderName;
		this.accountNumber = accountNumber;
		this.paymentStatus = paymentStatus;
		this.paymentUserMappings = paymentUserMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Payment_Status_Id", unique = true, nullable = false)
	public Integer getPaymentStatusId() {
		return this.paymentStatusId;
	}

	public void setPaymentStatusId(Integer paymentStatusId) {
		this.paymentStatusId = paymentStatusId;
	}

	@Column(name = "Payment_Type", length = 30)
	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "CardHolderName", length = 30)
	public String getCardHolderName() {
		return this.cardHolderName;
	}

	public void setCardHolderName(String cardHolderName) {
		this.cardHolderName = cardHolderName;
	}

	@Column(name = "Account_Number")
	public Long getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(Long accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "Payment_Status", length = 30)
	public String getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentStatus")
	public Set<PaymentUserMapping> getPaymentUserMappings() {
		return this.paymentUserMappings;
	}

	public void setPaymentUserMappings(Set<PaymentUserMapping> paymentUserMappings) {
		this.paymentUserMappings = paymentUserMappings;
	}

}
