package org.framework.entity;
// Generated 05 31, 18 11:14:50 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Pet generated by hbm2java
 */
@Entity
@Table(name = "pet", catalog = "petshop")
public class Pet implements java.io.Serializable {

	/**  @Author AdityaPandey
	 *   9 Jun 2018
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String breed;
	private String imagePath;
	private Double price;
	private String status;
	private Set<PaymentUserMapping> paymentUserMappings = new HashSet<PaymentUserMapping>(0);
	private PetDescription petDescription;

	public Pet() {
	}

	public Pet(String breed, String imagePath, Double price, String status, Set<PaymentUserMapping> paymentUserMappings,
			PetDescription petDescription) {
		this.breed = breed;
		this.imagePath = imagePath;
		this.price = price;
		this.status = status;
		this.paymentUserMappings = paymentUserMappings;
		this.petDescription = petDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Breed")
	public String getBreed() {
		return this.breed;
	}

	public void setBreed(String breed) {
		this.breed = breed;
	}

	@Column(name = "ImagePath")
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	@Column(name = "Price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pet")
	public Set<PaymentUserMapping> getPaymentUserMappings() {
		return this.paymentUserMappings;
	}

	public void setPaymentUserMappings(Set<PaymentUserMapping> paymentUserMappings) {
		this.paymentUserMappings = paymentUserMappings;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pet")
	public PetDescription getPetDescription() {
		return this.petDescription;
	}

	public void setPetDescription(PetDescription petDescription) {
		this.petDescription = petDescription;
	}

}
