package org.framework.entity;
// Generated 05 31, 18 11:14:50 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PetDescription generated by hbm2java
 */
@Entity
@Table(name = "pet_description", catalog = "petshop")
public class PetDescription implements java.io.Serializable {

	/**  @Author AdityaPandey
	 *   9 Jun 2018
	 */
	private static final long serialVersionUID = 1L;
	private Integer descriptionId;
	private Pet pet;
	private String gender;
	private String food;
	private String description;
	private String medicalCondition;

	public PetDescription() {
	}

	public PetDescription(Pet pet) {
		this.pet = pet;
	}

	public PetDescription(Pet pet, String gender, String food, String description, String medicalCondition) {
		this.pet = pet;
		this.gender = gender;
		this.food = food;
		this.description = description;
		this.medicalCondition = medicalCondition;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "pet"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "Description_ID", unique = true, nullable = false)
	public Integer getDescriptionId() {
		return this.descriptionId;
	}

	public void setDescriptionId(Integer descriptionId) {
		this.descriptionId = descriptionId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Pet getPet() {
		return this.pet;
	}

	public void setPet(Pet pet) {
		this.pet = pet;
	}

	@Column(name = "Gender", length = 30)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "Food", length = 500)
	public String getFood() {
		return this.food;
	}

	public void setFood(String food) {
		this.food = food;
	}

	@Column(name = "Description", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "MedicalCondition", length = 1000)
	public String getMedicalCondition() {
		return this.medicalCondition;
	}

	public void setMedicalCondition(String medicalCondition) {
		this.medicalCondition = medicalCondition;
	}

}
