package org.framework.entity;
// Generated 05 31, 18 11:14:50 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "petshop")
public class User implements java.io.Serializable {

	/**  @Author AdityaPandey
	 *   9 Jun 2018
	 */
	private static final long serialVersionUID = 1L;
	private Integer userId;
	private String userName;
	private String password;
	private String landMark;
	private Long pincode;
	private String district;
	private String city;
	private String state;
	private String roleType;
	private Set<PaymentUserMapping> paymentUserMappings = new HashSet<PaymentUserMapping>(0);

	public User() {
	}

	public User(String userName, String password, String landMark, Long pincode, String district, String city,
			String state, String roleType, Set<PaymentUserMapping> paymentUserMappings) {
		this.userName = userName;
		this.password = password;
		this.landMark = landMark;
		this.pincode = pincode;
		this.district = district;
		this.city = city;
		this.state = state;
		this.roleType = roleType;
		this.paymentUserMappings = paymentUserMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "User_Id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "UserName")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "Password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "LandMark")
	public String getLandMark() {
		return this.landMark;
	}

	public void setLandMark(String landMark) {
		this.landMark = landMark;
	}

	@Column(name = "Pincode")
	public Long getPincode() {
		return this.pincode;
	}

	public void setPincode(Long pincode) {
		this.pincode = pincode;
	}

	@Column(name = "District")
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "State")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Role_Type")
	public String getRoleType() {
		return this.roleType;
	}

	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<PaymentUserMapping> getPaymentUserMappings() {
		return this.paymentUserMappings;
	}

	public void setPaymentUserMappings(Set<PaymentUserMapping> paymentUserMappings) {
		this.paymentUserMappings = paymentUserMappings;
	}

}
